#!/usr/bin/env sh
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

#launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist

# window_zoom_persist off
# window_animation_duration 0.22
# normal_window_opacity 0.0
#
# global settings
yabai -m config \
	external_bar all:35:0 \
	menubar_opacity 0.5 \
	mouse_follows_focus off \
	focus_follows_mouse off \
	display_arrangement_order default window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_shadow on \
	window_animation_duration 0.22 \
	window_animation_easing ease_out_circ \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity off \
	insert_feedback_color 0xff9dd274 \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 20 \
	bottom_padding 10 \
	left_padding 10 \
	right_padding 10 \
	window_gap 05 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

yabai -m rule --add app="^(WezTerm)$" space=1
# yabai -m rule --add app="^(音乐)$" space=3
# yabai -m rule --add app="^(Google Chrome|Firefox Developer Edition)$" space=2

# Unmanaged apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^1Password 8$" manage=off
yabai -m rule --add app="^Skim$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Logi Options\+$" manage=off
yabai -m rule --add app="^Hidden Bar$" manage=off
yabai -m rule --add app="^The Unarchiver$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='^Archive Utility$' manage=off
yabai -m rule --add title='Settings$' manage=off

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Raycast" app="^Raycast$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Steam" app="^Steam$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# float system preferences. Most of these just diable Yabai form resizing them.

echo "yabai configuration loaded.."
