#!/bin/bash
# open terminal
alt - return : open -na /Applications/WezTerm.app/Contents/MacOS/wezterm-gui
# alt - return : open -na /Applications/Alacritty.app/Contents/MacOS/alacritty
# alt - return : open -na /Applications/iTerm.app/Contents/MacOS/iTerm2
# alt - return : /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~

# focus window
alt - h : yabai -m window --focus west || yabai -m display --focus west
alt - j : yabai -m window --focus south || yabai -m display --focus south || yabai -m window --focus stack.next
alt - k : yabai -m window --focus north || yabai -m display --focus north|| yabai -m window --focus stack.prev
alt - l : yabai -m window --focus east || yabai -m display --focus east
alt - n : yabai -m window --focus stack.next
alt - p : yabai -m window --focus stack.prev

## Window Movement (shift + alt - ...)
# Moving windows in spaces: shift + alt - {h, j, k, l}
shift + alt - h : yabai -m window --warp west || $(yabai -m window --display west && sketchybar --trigger windows_on_spaces && yabai -m display --focus west && yabai -m window --warp last) || yabai -m window --move rel:-10:0
shift + alt - j : yabai -m window --warp south || $(yabai -m window --display south && sketchybar --trigger windows_on_spaces && yabai -m display --focus south) || yabai -m window --move rel:0:10
shift + alt - k : yabai -m window --warp north || $(yabai -m window --display north && sketchybar --trigger windows_on_spaces && yabai -m display --focus north) || yabai -m window --move rel:0:-10
shift + alt - l: yabai -m window --warp east || $(yabai -m window --display east && sketchybar --trigger windows_on_spaces && yabai -m display --focus east && yabai -m window --warp first) || yabai -m window --move rel:10:0## Stacks (shift + ctrl - ...)

# Add the active window to the window or stack to the {direction}: shift + ctrl - {h, j, k, l}
shift + ctrl - h    : yabai -m window  west --stack $(yabai -m query --windows --window | jq -r '.id'); sketchybar --trigger window_focus
shift + ctrl - j    : yabai -m window south --stack $(yabai -m query --windows --window | jq -r '.id'); sketchybar --trigger window_focus
shift + ctrl - k    : yabai -m window north --stack $(yabai -m query --windows --window | jq -r '.id'); sketchybar --trigger window_focus
shift + ctrl - l : yabai -m window  east --stack $(yabai -m query --windows --window | jq -r '.id'); sketchybar --trigger window_focus

# set insertion point in focused container
ctrl + shift + alt - h : yabai -m window --insert west
ctrl + shift + alt - j : yabai -m window --insert south
ctrl + shift + alt - k : yabai -m window --insert north
ctrl + shift + alt - l : yabai -m window --insert east
ctrl + shift + alt - s : yabai -m window --insert stack

## Resize (ctrl + alt - ...)
# Resize windows: ctrl + alt - {h, j, k, l}
ctrl + lalt - h    : yabai -m window --resize right:-100:0 || yabai -m window --resize left:-100:0
ctrl + lalt - j    : yabai -m window --resize bottom:0:100 || yabai -m window --resize top:0:100
ctrl + lalt - k    : yabai -m window --resize bottom:0:-100 || yabai -m window --resize top:0:-100
ctrl + lalt - l : yabai -m window --resize right:100:0 || yabai -m window --resize left:100:0

# change layout of desktop
ctrl + alt - s : yabai -m space --layout stack
ctrl + alt - e : yabai -m space --layout bsp
ctrl + alt - f : yabai -m space --layout float

# Enable / Disable gaps in current workspace: ctrl + alt - g
ctrl + alt - g : yabai -m space --toggle padding; yabai -m space --toggle gapfloat
# Enable / Disable gaps in current workspace: ctrl + lalt - g
ctrl + alt - b : yabai -m config window_border off 
shift + ctrl + alt - b : yabai -m config window_border on

# toggle window fullscreen zoom
shift + alt - f : yabai -m window --toggle zoom-fullscreen; sketchybar --trigger window focus

# toggle float
shift + alt - t : yabai -m window --toggle float; sketchybar --trigger window_focus
# shift + alt - t : yabai -m window --toggle float --grid 4:4:1:1:2:2; sketchybar --trigger window_focus

# toggle picture-in-picture
shift + alt - p : yabai -m window --toggle border --toggle pip

# toggle topmost (keep above other windows)
shift + alt - o : yabai -m window --toggle topmost

# toggle sticky (show on all spaces)
shift + alt - s : yabai -m window --toggle sticky

# toggle window native fullscreen
# shift + alt - f : yabai -m window --toggle native-fullscreen

# fast focus desktop
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8
alt - 9 : yabai -m space --focus 9
alt - 0 : yabai -m space --focus 10

# alt - 1 : yabai -m space --focus 1;skhd -k "ctrl - 1"
# alt - 2 : yabai -m space --focus 2;skhd -k "ctrl - 2"
# alt - 3 : yabai -m space --focus 3;skhd -k "ctrl - 3"
# alt - 4 : yabai -m space --focus 4;skhd -k "ctrl - 4"
# alt - 5 : yabai -m space --focus 5;skhd -k "ctrl - 5"
# alt - 6 : yabai -m space --focus 6;skhd -k "ctrl - 6"
# alt - 7 : yabai -m space --focus 7;skhd -k "ctrl - 7"
# alt - 8 : yabai -m space --focus 8;skhd -k "ctrl - 8"
# alt - 9 : yabai -m space --focus 9;skhd -k "ctrl - 9"
# alt - 0 : yabai -m space --focus 10;skhd -k "ctrl - 0"

# send window to desktop
ctrl + alt - 1 : yabai -m window --space 1 && sketchybar --trigger windows_on_spaces
ctrl + alt - 2 : yabai -m window --space 2 && sketchybar --trigger windows_on_spaces
ctrl + alt - 3 : yabai -m window --space 3 && sketchybar --trigger windows_on_spaces
ctrl + alt - 4 : yabai -m window --space 4 && sketchybar --trigger windows_on_spaces
ctrl + alt - 5 : yabai -m window --space 5 && sketchybar --trigger windows_on_spaces
ctrl + alt - 6 : yabai -m window --space 6 && sketchybar --trigger windows_on_spaces
ctrl + alt - 7 : yabai -m window --space 7 && sketchybar --trigger windows_on_spaces
ctrl + alt - 8 : yabai -m window --space 8 && sketchybar --trigger windows_on_spaces
ctrl + alt - 9 : yabai -m window --space 9 && sketchybar --trigger windows_on_spaces
ctrl + alt - 0 : yabai -m window --space 10 && sketchybar --trigger windows_on_spaces

# send window to desktop and follow focus
shift + alt - 1 : yabai -m window --space  1; yabai -m space --focus 1; sketchybar --trigger windows_on_spaces
shift + alt - 2 : yabai -m window --space  2; yabai -m space --focus 2; sketchybar --trigger windows_on_spaces
shift + alt - 3 : yabai -m window --space  3; yabai -m space --focus 3; sketchybar --trigger windows_on_spaces
shift + alt - 4 : yabai -m window --space  4; yabai -m space --focus 4; sketchybar --trigger windows_on_spaces
shift + alt - 5 : yabai -m window --space  5; yabai -m space --focus 5; sketchybar --trigger windows_on_spaces
shift + alt - 6 : yabai -m window --space  6; yabai -m space --focus 6; sketchybar --trigger windows_on_spaces
shift + alt - 7 : yabai -m window --space  7; yabai -m space --focus 7; sketchybar --trigger windows_on_spaces
shift + alt - 8 : yabai -m window --space  8; yabai -m space --focus 8; sketchybar --trigger windows_on_spaces
shift + alt - 9 : yabai -m window --space  9; yabai -m space --focus 9; sketchybar --trigger windows_on_spaces
shift + alt - 0 : yabai -m window --space 10; yabai -m space --focus 10; sketchybar --trigger windows_on_spaces
shift + alt - p : yabai -m window --space prev; yabai -m space --focus prev; sketchybar --trigger windows_on_spaces
shift + alt - n : yabai -m window --space next; yabai -m space --focus next; sketchybar --trigger windows_on_spaces


# rotate tree
ctrl + alt - r : yabai -m space --rotate 90

# mirror tree y-axis
shift + alt - y : yabai -m space --mirror y-axis

# mirror tree x-axis
shift + alt - x : yabai -m space --mirror x-axis

# Stack Navigation: shift + ctrl - {n, p}
shift + ctrl - n : yabai -m window --focus stack.next
shift + ctrl - p : yabai -m window --focus stack.prev

alt - v : yabai -m window --toggle split

# Restart Yabai
shift + alt - r : \
    yabai --restart-service; \
    launchctl kickstart -k "gui/${UID}/homebrew.mxcl.sketchybar"

shift + alt - s : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.sketchybar"
shift +ctrl - e : ~/.emacs.d/bin/doom +everywhere
