return {
  -- {
  --   "ahmedkhalf/project.nvim",
  --   version = false,
  --   opts = {
  --     manual_mode = false, -- automactically add
  --   },
  --   event = "VeryLazy",
  --   config = function(_, opts)
  --     opts.detection_methods = { "lsp", "pattern" }
  --     opts.patterns = {
  --       ".git",
  --       "=src",
  --       "_darcs",
  --       ".hg",
  --       ".bzr",
  --       ".svn",
  --       "Makefile",
  --       "package.json",
  --     }
  --     require("project_nvim").setup(opts)
  --     require("lazyvim.util").on_load("telescope.nvim", function()
  --       require("telescope").load_extension("projects")
  --     end)
  --   end,
  --   keys = {
  --     { "<leader>fp", "<Cmd>Telescope projects<CR>", desc = "Projects" },
  --   },
  -- },
}
